#!/usr/bin/env python3
"""
Research Paper Management Tool
Organizes research papers with unique identifiers and maintains a local database.
"""

import os
import json
import random
import string
import argparse
import sys
from datetime import datetime
from pathlib import Path

class ResearchManager:
    def __init__(self, base_dir="."):
        self.base_dir = Path(base_dir)
        self.db_file = self.base_dir / "research_db.json"
        self.main_readme = self.base_dir / "README.md"
        self.ensure_setup()
    
    def ensure_setup(self):
        """Ensure the base directory and database file exist."""
        self.base_dir.mkdir(exist_ok=True)
        if not self.db_file.exists():
            self._init_database()
        if not self.main_readme.exists():
            self._init_main_readme()
    
    def _init_database(self):
        """Initialize the database file."""
        initial_data = {
            "papers": {},
            "metadata": {
                "created": datetime.now().isoformat(),
                "total_papers": 0
            }
        }
        with open(self.db_file, 'w') as f:
            json.dump(initial_data, f, indent=2)
    
    def _init_main_readme(self):
        """Initialize the main README file."""
        content = """# Research Papers Collection

This directory contains organized research papers with unique identifiers.

## Papers Index

| ID | Title | Author |
|----|-------|--------|

---
*Generated by Research Manager Tool*
"""
        with open(self.main_readme, 'w') as f:
            f.write(content)
    
    def generate_identifier(self, author_name):
        """
        Generate a unique identifier with author initials + random characters.
        Format: XX####XX (Author initials + 4 digits + 2 letters)
        """
        # Extract initials from author name
        names = author_name.strip().split()
        if len(names) >= 2:
            initials = names[0][0].upper() + names[-1][0].upper()
        elif len(names) == 1:
            initials = names[0][:2].upper()
        else:
            initials = "XX"
        
        # Ensure we have exactly 2 characters
        initials = (initials + "XX")[:2]
        
        # Generate random part: 4 digits + 2 letters
        digits = ''.join(random.choices(string.digits, k=4))
        letters = ''.join(random.choices(string.ascii_uppercase, k=2))
        
        identifier = f"{initials}{digits}{letters}"
        
        # Ensure uniqueness
        data = self._load_database()
        while identifier in data["papers"]:
            digits = ''.join(random.choices(string.digits, k=4))
            letters = ''.join(random.choices(string.ascii_uppercase, k=2))
            identifier = f"{initials}{digits}{letters}"
        
        return identifier
    
    def _load_database(self):
        """Load the database from file."""
        try:
            with open(self.db_file, 'r') as f:
                return json.load(f)
        except (FileNotFoundError, json.JSONDecodeError):
            self._init_database()
            with open(self.db_file, 'r') as f:
                return json.load(f)
    
    def _save_database(self, data):
        """Save the database to file."""
        with open(self.db_file, 'w') as f:
            json.dump(data, f, indent=2)
    
    def _create_paper_readme(self, paper_id, title, author):
        """Create README for individual paper."""
        paper_dir = self.base_dir / paper_id
        readme_path = paper_dir / "README.md"
        
        content = f"""# {title}

**Author:** {author}  
**Paper ID:** {paper_id}  
**Date Added:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Abstract

[Add your abstract here]

## Files

- `manuscript.pdf` - Main manuscript file
- `figures/` - Directory for figures and images
- `data/` - Directory for datasets and supplementary data
- `code/` - Directory for code and scripts

## Notes

[Add your research notes here]

### License

{title} © {datetime.now().strftime('%Y')} by {author} is licensed under CC BY-SA 4.0. To view a copy of this license, visit https://creativecommons.org/licenses/by-sa/4.0/

---
*Generated by Research Manager Tool*
"""
        
        with open(readme_path, 'w') as f:
            f.write(content)
        
        return readme_path
    
    def _update_main_readme(self):
        """Update the main README with current papers index."""
        data = self._load_database()
        
        header = """# Research Papers Collection

This directory contains organized research papers with unique identifiers.

## Papers Index

| ID | Title | Author |
|----|-------|--------|
"""
        
        rows = []
        for paper_id, paper_info in sorted(data["papers"].items()):
            title = paper_info["title"]
            author = paper_info["author"]
            id_link = f"[{paper_id}](./{paper_id}/README.md)"
            
            rows.append(f"| {id_link} | {title} | {author} |")
        
        footer = f"""

---
**Total Papers:** {len(data['papers'])}  
*Last Updated:* {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
*Generated by Research Manager Tool*
"""
        
        content = header + '\n'.join(rows) + footer
        
        with open(self.main_readme, 'w') as f:
            f.write(content)
    
    def interactive_add_paper(self):
        """Interactive CLI for adding a new research paper."""
        print("📝 Add New Research Paper")
        print("=" * 40)
        
        # Get title
        while True:
            title = input("📋 Enter paper title: ").strip()
            if title:
                break
            print("❌ Title cannot be empty. Please try again.")
        
        # Get author
        while True:
            author = input("👤 Enter primary author name: ").strip()
            if author:
                break
            print("❌ Author name cannot be empty. Please try again.")
        
        # Confirm before creating
        print(f"\n📊 Summary:")
        print(f"   Title: {title}")
        print(f"   Author: {author}")
        
        while True:
            confirm = input("\n✅ Create this paper entry? (y/n): ").strip().lower()
            if confirm in ['y', 'yes']:
                break
            elif confirm in ['n', 'no']:
                print("❌ Paper creation cancelled.")
                return None
            else:
                print("Please enter 'y' or 'n'.")
        
        # Create the paper
        paper_id = self.add_paper(title, author)
        
        # Success message with instructions
        print(f"\n🎉 Paper created successfully!")
        print(f"📋 Paper ID: {paper_id}")
        print(f"📁 Directory: {paper_id}/")
        print(f"📄 README: {paper_id}/README.md")
        print(f"\n📝 Next steps:")
        print(f"   1. cd {paper_id}")
        print(f"   2. Add your manuscript files to the directory")
        print(f"   3. Update the README.md with your abstract and notes")
        print(f"   4. Organize files in the subdirectories:")
        print(f"      - figures/ (for images and diagrams)")
        print(f"      - data/ (for datasets)")
        print(f"      - code/ (for scripts and programs)")
        
        return paper_id
    
    def add_paper(self, title, author):
        """Add a new research paper."""
        # Generate unique identifier
        paper_id = self.generate_identifier(author)
        
        # Create directory structure
        paper_dir = self.base_dir / paper_id
        paper_dir.mkdir(exist_ok=True)
        
        # Create subdirectories
        (paper_dir / "figures").mkdir(exist_ok=True)
        (paper_dir / "data").mkdir(exist_ok=True)
        (paper_dir / "code").mkdir(exist_ok=True)
        
        # Create paper README
        readme_path = self._create_paper_readme(paper_id, title, author)
        
        # Update database
        data = self._load_database()
        data["papers"][paper_id] = {
            "title": title,
            "author": author,
            "date_added": datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            "directory": str(paper_dir),
            "readme_path": str(readme_path)
        }
        data["metadata"]["total_papers"] = len(data["papers"])
        self._save_database(data)
        
        # Update main README
        self._update_main_readme()
        
        return paper_id
    
    def remove_paper(self, paper_id):
        """Remove a research paper."""
        data = self._load_database()
        
        if paper_id not in data["papers"]:
            return False, f"Paper with ID '{paper_id}' not found."
        
        # Remove directory
        paper_dir = self.base_dir / paper_id
        if paper_dir.exists():
            import shutil
            shutil.rmtree(paper_dir)
        
        # Remove from database
        del data["papers"][paper_id]
        data["metadata"]["total_papers"] = len(data["papers"])
        self._save_database(data)
        
        # Update main README
        self._update_main_readme()
        
        return True, f"Paper '{paper_id}' removed successfully."
    
    def view_papers(self, paper_id=None):
        """View papers (all or specific)."""
        data = self._load_database()
        
        if paper_id:
            if paper_id in data["papers"]:
                return data["papers"][paper_id]
            else:
                return None
        else:
            return data["papers"]
    
    def search_papers(self, query):
        """Search papers by title or author."""
        data = self._load_database()
        results = {}
        
        query_lower = query.lower()
        for paper_id, paper_info in data["papers"].items():
            if (query_lower in paper_info["title"].lower() or 
                query_lower in paper_info["author"].lower()):
                results[paper_id] = paper_info
        
        return results

def main():
    parser = argparse.ArgumentParser(description="Research Paper Management Tool")
    parser.add_argument("--dir", default=".", help="Base directory for research papers")
    
    subparsers = parser.add_subparsers(dest="command", help="Available commands")
    
    # Add command - now interactive by default
    add_parser = subparsers.add_parser("add", help="Add a new research paper (interactive)")
    add_parser.add_argument("--title", help="Title of the research paper (non-interactive)")
    add_parser.add_argument("--author", help="Primary author name (non-interactive)")
    
    # Remove command
    remove_parser = subparsers.add_parser("remove", help="Remove a research paper")
    remove_parser.add_argument("paper_id", help="Paper ID to remove")
    
    # View command
    view_parser = subparsers.add_parser("view", help="View research papers")
    view_parser.add_argument("paper_id", nargs="?", help="Specific paper ID to view")
    
    # Search command
    search_parser = subparsers.add_parser("search", help="Search research papers")
    search_parser.add_argument("query", help="Search query (title or author)")
    
    args = parser.parse_args()
    
    if not args.command:
        parser.print_help()
        return
    
    rm = ResearchManager(args.dir)
    
    if args.command == "add":
        if args.title and args.author:
            # Non-interactive mode (for scripts/automation)
            paper_id = rm.add_paper(args.title, args.author)
            print(f"✅ Paper added successfully!")
            print(f"📋 Paper ID: {paper_id}")
            print(f"📁 Directory: {paper_id}/")
        else:
            # Interactive mode (default)
            rm.interactive_add_paper()
    
    elif args.command == "remove":
        success, message = rm.remove_paper(args.paper_id)
        if success:
            print(f"✅ {message}")
        else:
            print(f"❌ {message}")
    
    elif args.command == "view":
        if args.paper_id:
            paper = rm.view_papers(args.paper_id)
            if paper:
                print(f"📋 Paper ID: {args.paper_id}")
                print(f"📝 Title: {paper['title']}")
                print(f"👤 Author: {paper['author']}")
                print(f"📅 Date Added: {paper['date_added']}")
                print(f"📁 Directory: {paper['directory']}")
            else:
                print(f"❌ Paper with ID '{args.paper_id}' not found.")
        else:
            papers = rm.view_papers()
            if papers:
                print("📚 Research Papers:")
                print("-" * 80)
                for paper_id, paper_info in sorted(papers.items()):
                    print(f"📋 {paper_id} | {paper_info['title']} | {paper_info['author']}")
                print(f"\n📊 Total: {len(papers)} papers")
            else:
                print("📚 No papers found.")
    
    elif args.command == "search":
        results = rm.search_papers(args.query)
        if results:
            print(f"🔍 Search results for '{args.query}':")
            print("-" * 80)
            for paper_id, paper_info in results.items():
                print(f"📋 {paper_id} | {paper_info['title']} | {paper_info['author']}")
            print(f"\n📊 Found: {len(results)} papers")
        else:
            print(f"🔍 No papers found matching '{args.query}'")

if __name__ == "__main__":
    main()
